export const palette = {
    background: '#fbf7f3',
    surface: '#f6efeb',
    card: '#ffffff',
    border: '#e8dfda',
    text: '#262126',
    muted: '#746e77',
    primary: '#c11e38',
    primaryDeep: '#220b34',
    secondary: '#cb9c48',
    teal: '#2d8c83',
    green: '#2f9367',
    blue: '#3774d8',
    purple: '#8856c9',
    orange: '#ea872e',
    pink: '#d9608f',
    danger: '#d04f4f',
};
export const studentProfile = {
    name: 'Aarav Sharma',
    email: 'aarav.sharma@email.com',
    mobile: '+91 98765 43210',
    standard: 'Class 11',
    stream: 'Science',
    subscription: 'Psychometric + Counselling',
};
export const existingUsers = [
    {
        id: 'user-1',
        name: 'Jayashree Das',
        mobile: '9876543210',
        email: 'jaya@email.com',
        password: 'Jaya@123',
        coupon: 'CAREER2026',
    },
    {
        id: 'user-2',
        name: 'Priya Parent',
        mobile: '9988776655',
        email: 'priya.parent@email.com',
        password: 'Parent@123',
        coupon: 'PARENTMAP',
    },
];
export const heroStats = [
    { label: 'Saved Careers', value: '18', tone: palette.orange },
    { label: 'Tests Taken', value: '06', tone: palette.blue },
    { label: 'Mentor Sessions', value: '03', tone: palette.purple },
];
export const moduleCards = [
    {
        title: 'Career Library',
        subtitle: 'Explore streams, roles, and college paths.',
        icon: 'book-outline',
        route: '/(drawer)/(tabs)/library',
        tone: palette.blue,
    },
    {
        title: 'Assessment',
        subtitle: 'Discover aptitude and personality insights.',
        icon: 'analytics-outline',
        route: '/(drawer)/(tabs)/assessment',
        tone: palette.purple,
    },
    {
        title: 'Master Class',
        subtitle: 'Short expert-led learning videos.',
        icon: 'school-outline',
        route: '/(drawer)/(tabs)/learn',
        tone: palette.orange,
    },
    {
        title: 'Entrance Exam',
        subtitle: 'Practice tests and exam preparation guides.',
        icon: 'clipboard-outline',
        route: '/(drawer)/entrance-exam',
        tone: palette.teal,
    },
    {
        title: 'Institutes',
        subtitle: 'Browse top colleges and universities.',
        icon: 'business-outline',
        route: '/(drawer)/institute',
        tone: palette.pink,
    },
    {
        title: 'Book Mentor',
        subtitle: 'Reserve guidance with an expert mentor.',
        icon: 'people-outline',
        route: '/(drawer)/book-mentor',
        tone: palette.secondary,
    },
    {
        title: 'Scholarships',
        subtitle: 'Funding alerts and application deadlines.',
        icon: 'ribbon-outline',
        route: '/(drawer)/scholarship',
        tone: palette.green,
    },
    {
        title: 'Quiz',
        subtitle: 'Test your knowledge with fun quizzes.',
        icon: 'help-circle-outline',
        route: '/(drawer)/quiz',
        tone: palette.blue,
    },
    {
        title: 'Study Abroad',
        subtitle: 'Explore international education options.',
        icon: 'globe-outline',
        route: '/(drawer)/abroad',
        tone: palette.purple,
    },
];
export const entranceExams = [
    {
        id: 'jee-main',
        name: 'JEE Main',
        authority: 'NTA',
        date: 'April 2025',
        eligibility: 'Class 12 pass (PCM)',
        type: 'Central',
        category: 'Engineering',
        mode: 'Computer Based',
        duration: '3 Hours',
        subjects: 'Physics, Chemistry, Mathematics',
        totalMarks: '300',
        frequency: '2 times/year',
        about: 'Joint Entrance Examination for admission to NITs, IIITs, and other CFTIs. One of India\'s most competitive engineering entrance exams.',
        examPattern: ['Paper 1: 75 MCQ + Numerical', 'Negative marking: -1 for wrong MCQ', 'No negative marking for numerical'],
        topColleges: ['NIT Trichy', 'NIT Warangal', 'NIT Surathkal', 'IIIT Hyderabad'],
        website: 'https://jeemain.nta.nic.in/',
    },
    {
        id: 'neet-ug',
        name: 'NEET UG',
        authority: 'NTA',
        date: 'May 2025',
        eligibility: 'Class 12 pass (PCB)',
        type: 'Central',
        category: 'Medical',
        mode: 'Pen and Paper',
        duration: '3 Hours 20 Minutes',
        subjects: 'Physics, Chemistry, Botany, Zoology',
        totalMarks: '720',
        frequency: '1 time/year',
        about: 'National Eligibility cum Entrance Test for admission into MBBS, BDS, AYUSH, and related undergraduate medical programs across India.',
        examPattern: ['200 questions, 180 to be attempted', '4 marks for correct answer', 'Negative marking: -1 for wrong answer'],
        topColleges: ['AIIMS Delhi', 'JIPMER Puducherry', 'MMC Chennai', 'KGMU Lucknow'],
        website: 'https://neet.nta.nic.in/',
    },
    {
        id: 'clat',
        name: 'CLAT',
        authority: 'Consortium of NLUs',
        date: 'December 2024',
        eligibility: 'Class 12 pass',
        type: 'Central',
        category: 'Law',
        mode: 'Offline',
        duration: '2 Hours',
        subjects: 'English, Legal Reasoning, GK, Logic, Quantitative Techniques',
        totalMarks: '120',
        frequency: '1 time/year',
        about: 'Common Law Admission Test for undergraduate and postgraduate law admissions in National Law Universities and affiliated institutions.',
        examPattern: ['120 passage-based MCQs', 'Negative marking: -0.25 for incorrect answer', 'Strong emphasis on reading comprehension'],
        topColleges: ['NLSIU Bengaluru', 'NLU Delhi', 'NALSAR Hyderabad', 'WBNUJS Kolkata'],
        website: 'https://consortiumofnlus.ac.in/',
    },
    {
        id: 'cuet',
        name: 'CUET',
        authority: 'NTA',
        date: 'May 2025',
        eligibility: 'Class 12 pass',
        type: 'Central',
        category: 'General',
        mode: 'Computer Based',
        duration: 'Varies by subject',
        subjects: 'Language, Domain Subjects, General Test',
        totalMarks: 'Subject-wise',
        frequency: '1 time/year',
        about: 'Common University Entrance Test for undergraduate admissions to central universities and many participating institutions.',
        examPattern: ['Multiple subject combinations allowed', 'MCQ-based test', 'Choice depends on target university and course'],
        topColleges: ['Delhi University', 'BHU', 'JMI', 'University of Hyderabad'],
        website: 'https://cuet.nta.nic.in/',
    },
    {
        id: 'bitsat',
        name: 'BITSAT',
        authority: 'BITS Pilani',
        date: 'May 2025',
        eligibility: 'Class 12 (PCM)',
        type: 'Private',
        category: 'Engineering',
        mode: 'Computer Based',
        duration: '3 Hours',
        subjects: 'Physics, Chemistry, English, Logical Reasoning, Mathematics',
        totalMarks: '390',
        frequency: '2 sessions/year',
        about: 'BITS Admission Test for admission to integrated first-degree programs at BITS Pilani campuses.',
        examPattern: ['130 questions', 'Bonus questions available after completing all questions', 'Negative marking: -1 for incorrect answer'],
        topColleges: ['BITS Pilani', 'BITS Goa', 'BITS Hyderabad'],
        website: 'https://www.bitsadmission.com/',
    },
    {
        id: 'cat',
        name: 'CAT',
        authority: 'IIMs',
        date: 'November 2025',
        eligibility: 'Graduate',
        type: 'Central',
        category: 'Business',
        mode: 'Computer Based',
        duration: '2 Hours',
        subjects: 'VARC, DILR, Quantitative Aptitude',
        totalMarks: '198',
        frequency: '1 time/year',
        about: 'Common Admission Test for MBA and management admissions in IIMs and many leading business schools.',
        examPattern: ['Section-timed exam', 'MCQ + TITA questions', 'Negative marking for MCQs only'],
        topColleges: ['IIM Ahmedabad', 'IIM Bangalore', 'IIM Calcutta', 'FMS Delhi'],
        website: 'https://iimcat.ac.in/',
    },
    {
        id: 'mht-cet',
        name: 'MHT CET',
        authority: 'Maharashtra Govt',
        date: 'May 2025',
        eligibility: 'Class 12 (PCM/PCB)',
        type: 'State',
        category: 'Engineering',
        mode: 'Computer Based',
        duration: '180 Minutes',
        subjects: 'Physics, Chemistry, Mathematics/Biology',
        totalMarks: '200',
        frequency: '1 time/year',
        about: 'State-level entrance exam for engineering, pharmacy, and allied admissions across Maharashtra colleges.',
        examPattern: ['Separate PCM and PCB groups', 'No negative marking', 'Difficulty closer to JEE Main for PCM'],
        topColleges: ['COEP Pune', 'VJTI Mumbai', 'ICT Mumbai'],
        website: 'https://cetcell.mahacet.org/',
    },
    {
        id: 'kcet',
        name: 'KCET',
        authority: 'Karnataka Govt',
        date: 'April 2025',
        eligibility: 'Class 12 pass',
        type: 'State',
        category: 'Engineering',
        mode: 'Offline',
        duration: '80 Minutes per paper',
        subjects: 'Physics, Chemistry, Mathematics, Biology',
        totalMarks: '180',
        frequency: '1 time/year',
        about: 'Karnataka Common Entrance Test for admissions to engineering, pharmacy, agriculture, and allied courses in Karnataka.',
        examPattern: ['60 questions per subject', 'No negative marking', 'Separate papers across subjects'],
        topColleges: ['RVCE', 'PES University', 'BMSCE'],
        website: 'https://kea.kar.nic.in/',
    },
    {
        id: 'aiims-ini-cet',
        name: 'AIIMS INI CET',
        authority: 'AIIMS',
        date: 'July 2025',
        eligibility: 'MBBS pass',
        type: 'Central',
        category: 'Medical',
        mode: 'Computer Based',
        duration: '3 Hours',
        subjects: 'Clinical, Pre-clinical, Para-clinical subjects',
        totalMarks: '200',
        frequency: '2 times/year',
        about: 'Institute of National Importance Combined Entrance Test for postgraduate medical admissions at AIIMS and partner institutes.',
        examPattern: ['200 MCQs', 'Negative marking: -1/3 for incorrect answer', 'Covers MBBS curriculum comprehensively'],
        topColleges: ['AIIMS Delhi', 'JIPMER', 'PGIMER Chandigarh'],
        website: 'https://www.aiimsexams.ac.in/',
    },
    {
        id: 'nift-entrance',
        name: 'NIFT Entrance',
        authority: 'NIFT',
        date: 'February 2025',
        eligibility: 'Class 12 pass',
        type: 'Central',
        category: 'Design',
        mode: 'Computer Based + Studio Test',
        duration: 'Varies by stage',
        subjects: 'GAT, CAT, Situation Test/Interview',
        totalMarks: 'Stage-based',
        frequency: '1 time/year',
        about: 'National Institute of Fashion Technology entrance process for design, fashion technology, and related creative programs.',
        examPattern: ['General Ability Test plus Creative Ability Test', 'Additional studio or interview rounds for select programs', 'Strong design aptitude focus'],
        topColleges: ['NIFT Delhi', 'NIFT Mumbai', 'NIFT Bengaluru'],
        website: 'https://www.nift.ac.in/',
    },
    {
        id: 'gate',
        name: 'GATE',
        authority: 'IIT',
        date: 'February 2026',
        eligibility: 'B.Tech/B.E.',
        type: 'Central',
        category: 'Engineering',
        mode: 'Computer Based',
        duration: '3 Hours',
        subjects: 'General Aptitude + Core Subject',
        totalMarks: '100',
        frequency: '1 time/year',
        about: 'Graduate Aptitude Test in Engineering for postgraduate admissions, PSU recruitment, and technical higher studies.',
        examPattern: ['MCQ, MSQ, and NAT questions', 'Partial negative marking applies to select questions', 'Score valid for 3 years'],
        topColleges: ['IISc Bangalore', 'IIT Bombay', 'IIT Delhi', 'IIT Madras'],
        website: 'https://gate2026.iitr.ac.in/',
    },
    {
        id: 'viteee',
        name: 'VITEEE',
        authority: 'VIT',
        date: 'April 2025',
        eligibility: 'Class 12 (PCM)',
        type: 'Private',
        category: 'Engineering',
        mode: 'Computer Based',
        duration: '2 Hours 30 Minutes',
        subjects: 'Physics, Chemistry, Mathematics/Biology, Aptitude, English',
        totalMarks: '125',
        frequency: '1 time/year',
        about: 'VIT Engineering Entrance Examination for admission to undergraduate engineering programs across VIT campuses.',
        examPattern: ['125 questions', 'No negative marking', 'Includes aptitude and English sections'],
        topColleges: ['VIT Vellore', 'VIT Chennai', 'VIT AP'],
        website: 'https://viteee.vit.ac.in/',
    },
];
export const streamCards = [
    { title: 'Science', emoji: 'Science', description: 'Medical, engineering, and research pathways.', tone: palette.blue },
    { title: 'Commerce', emoji: 'Commerce', description: 'Business, banking, management, and finance.', tone: palette.green },
    { title: 'Arts & Humanities', emoji: 'Arts', description: 'Design, media, writing, social impact, and law.', tone: palette.orange },
    { title: 'Vocational', emoji: 'Skills', description: 'Applied programs in hospitality, fashion, and trades.', tone: palette.pink },
];
export const featuredCareers = [
    {
        title: 'Computer Science Engineering',
        fit: 'Analytical + systems thinking',
        description: 'Build software, platforms, and intelligent products across web, mobile, AI, and cloud.',
        tag: 'Technology',
    },
    {
        title: 'General Medicine',
        fit: 'Empathy + scientific curiosity',
        description: 'Treat patients, diagnose conditions, and build long-term impact in healthcare.',
        tag: 'Medical',
    },
    {
        title: 'UX Design',
        fit: 'Creative + user-focused',
        description: 'Shape digital experiences with research, interaction design, and visual systems.',
        tag: 'Design',
    },
    {
        title: 'MBA Finance',
        fit: 'Business + numbers',
        description: 'Work in investment, planning, consulting, and leadership roles across industries.',
        tag: 'Business',
    },
];
export const featuredMentors = [
    { name: 'Dr. Priya Sharma', specialty: 'Career Counselling', rating: '4.9', experience: '12 yrs', accent: palette.primary },
    { name: 'Prof. Rahul Verma', specialty: 'Engineering', rating: '4.8', experience: '15 yrs', accent: palette.blue },
    { name: 'Ms. Anjali Singh', specialty: 'Design & Arts', rating: '4.7', experience: '8 yrs', accent: palette.orange },
];
export const featuredScholarships = [
    { name: 'INSPIRE Scholarship', amount: 'Rs 80,000 / year', deadline: 'March 2025', tag: 'Merit Based' },
    { name: 'KVPY Fellowship', amount: 'Rs 7,000 / month', deadline: 'August 2025', tag: 'Science' },
    { name: 'Pragati Scholarship', amount: 'Rs 50,000 / year', deadline: 'December 2024', tag: 'Girls in Tech' },
];
export const featuredInstitutes = [
    { name: 'IIT Bombay', location: 'Mumbai', type: 'Engineering' },
    { name: 'AIIMS Delhi', location: 'New Delhi', type: 'Medical' },
    { name: 'IIM Ahmedabad', location: 'Ahmedabad', type: 'Business' },
];
export const scholarships = [
    {
        name: 'INSPIRE Scholarship',
        eligibility: 'Top 1% in Class 12 Board Exams',
        amount: 'Rs 80,000 / year',
        deadline: 'March 2025',
        tag: 'Merit Based',
        status: 'Active',
        provider: 'Department of Science & Technology',
        description: 'Innovation in Science Pursuit for Inspired Research supports tuition and research expenses for BSc, MSc, and PhD students in natural and basic sciences.',
        requirements: ['Top 1% in Class 12', 'Pursuing BSc, MSc, or PhD in natural sciences', 'Indian citizen'],
        link: 'https://online-inspire.gov.in',
    },
    {
        name: 'National Talent Search (NTSE)',
        eligibility: 'Class 10 students',
        amount: 'Rs 1,250 / month',
        deadline: 'November 2024',
        tag: 'National',
        status: 'Expired',
        provider: 'NCERT',
        description: 'Identifies and nurtures talented students at Class 10 level through a two-stage selection process at the state and national levels.',
        requirements: ['Class 10 student', 'Indian nationality', 'Clear Stage 1 at state level'],
        link: 'https://ncert.nic.in/ntse',
    },
    {
        name: 'KVPY Fellowship',
        eligibility: 'Class 11-12 Science students',
        amount: 'Rs 7,000 / month',
        deadline: 'August 2025',
        tag: 'Science',
        status: 'Active',
        provider: 'IISc Bangalore',
        description: 'Kishore Vaigyanik Protsahan Yojana encourages students to pursue research careers and includes enrichment opportunities at leading institutions.',
        requirements: ['Studying in Class 11, 12, or first-year BSc', 'Science stream', 'Clear aptitude test and interview'],
        link: 'https://kvpy.iisc.ac.in',
    },
    {
        name: 'Pragati Scholarship',
        eligibility: 'Girl students in technical education',
        amount: 'Rs 50,000 / year',
        deadline: 'December 2024',
        tag: 'Girls in Tech',
        status: 'Expired',
        provider: 'AICTE',
        description: 'Supports girls in technical education with financial assistance for tuition fees, books, and learning equipment.',
        requirements: ['Female candidate', 'Admitted to AICTE-approved institution', 'Family income below Rs 8 LPA'],
        link: 'https://scholarships.gov.in',
    },
    {
        name: 'Central Sector Scholarship',
        eligibility: 'Class 12 passout - top 20% in Board',
        amount: 'Rs 12,000 / year',
        deadline: 'October 2025',
        tag: 'National',
        status: 'Active',
        provider: 'Ministry of Education',
        description: 'For meritorious students from economically weaker sections, covering graduation and post-graduation study support.',
        requirements: ['Above 80th percentile in Class 12', 'Family income below Rs 8 LPA', 'Pursuing a regular degree'],
        link: 'https://scholarships.gov.in',
    },
    {
        name: 'Aditya Birla Scholarship',
        eligibility: 'Top institution students',
        amount: 'Rs 1,00,000 / year',
        deadline: 'June 2025',
        tag: 'Corporate',
        status: 'Expired',
        provider: 'Aditya Birla Group',
        description: 'A prestigious scholarship for students admitted to IITs, IIMs, BITS, XLRI, and other leading institutes in India.',
        requirements: ['Admission to a premier institution', 'Outstanding academic record', 'Clear interview round'],
        link: 'https://scholarships.gov.in',
    },
    {
        name: 'Tata Trusts Scholarship',
        eligibility: 'Professional course students',
        amount: 'Rs 50,000 / year',
        deadline: 'September 2025',
        tag: 'Corporate',
        status: 'Expired',
        provider: 'Tata Trusts',
        description: 'Supports students in professional courses including engineering, medicine, and management at reputed institutions.',
        requirements: ['Admission in professional course', 'Financial need', 'Good academic record'],
        link: 'https://scholarships.gov.in',
    },
    {
        name: 'L&T Build India Scholarship',
        eligibility: 'Engineering students',
        amount: 'Rs 75,000 / year',
        deadline: 'March 2025',
        tag: 'Corporate',
        status: 'Closed',
        provider: 'Larsen & Toubro',
        description: 'For engineering students interested in infrastructure careers, with tuition support and mentorship.',
        requirements: ['First-year engineering student', 'AICTE-approved college', 'Family income below Rs 6 LPA'],
        link: 'https://scholarships.gov.in',
    },
];
export const institutes = [
    {
        name: 'IIT Bombay',
        location: 'Mumbai, Maharashtra',
        courses: ['B.Tech', 'M.Tech', 'PhD'],
        rank: '#1',
        type: 'Engineering',
        career: 'Engineering',
        icon: 'school-outline',
        about: 'One of India\'s premier engineering institutions known for strong academics, research, and innovation.',
        website: 'https://www.iitb.ac.in',
    },
    {
        name: 'AIIMS Delhi',
        location: 'New Delhi',
        courses: ['MBBS', 'MD', 'MS'],
        rank: '#1',
        type: 'Medical',
        career: 'Medical',
        icon: 'medkit-outline',
        about: 'India\'s most recognised medical institute with top clinical training, research exposure, and healthcare leadership.',
        website: 'https://www.aiims.edu',
    },
    {
        name: 'IIM Ahmedabad',
        location: 'Ahmedabad, Gujarat',
        courses: ['MBA', 'PGPX'],
        rank: '#1',
        type: 'Business',
        career: 'Business',
        icon: 'briefcase-outline',
        about: 'A leading business school with world-class faculty, rigorous management training, and strong industry links.',
        website: 'https://www.iima.ac.in',
    },
    {
        name: 'NID Ahmedabad',
        location: 'Ahmedabad, Gujarat',
        courses: ['B.Des', 'M.Des'],
        rank: '#1',
        type: 'Design',
        career: 'Design',
        icon: 'color-palette-outline',
        about: 'A top destination for students pursuing design, creative practice, and innovation-led product thinking.',
        website: 'https://www.nid.edu',
    },
    {
        name: 'BITS Pilani',
        location: 'Pilani, Rajasthan',
        courses: ['B.E.', 'M.E.'],
        rank: '#4',
        type: 'Engineering',
        career: 'Engineering',
        icon: 'flash-outline',
        about: 'Known for flexible academics, entrepreneurship culture, and excellent placement opportunities.',
        website: 'https://www.bits-pilani.ac.in',
    },
    {
        name: 'NLU Delhi',
        location: 'New Delhi',
        courses: ['BA LLB', 'LLM'],
        rank: '#1',
        type: 'Law',
        career: 'Law',
        icon: 'scale-outline',
        about: 'A leading law university with strong academic rigor, moot culture, and policy exposure.',
        website: 'https://nludelhi.ac.in',
    },
];
export const assessmentFeatures = [
    '50 MCQ questions',
    'Aptitude and personality analysis',
    'AI-powered career matching',
    'Detailed report summary',
    'One-year validity per plan',
];
export const assessmentPolicies = [
    'Each subscription includes 1 psychometric test.',
    'Test validity lasts 1 year from purchase date.',
    'A new purchase is required for a retake.',
    'Study Abroad Access unlocks only the abroad module.',
];
export const masterClasses = [
    {
        title: 'How to Choose the Right Engineering Branch',
        mentor: 'Dr. Rajesh Kumar',
        duration: '15 min',
        views: 12400,
        career: 'Engineering',
        videoType: 'Career Videos',
        locked: false,
        url: 'https://www.youtube.com/watch?v=H14bBuluwB8',
    },
    {
        title: 'NEET 2025 - Complete Roadmap',
        mentor: 'Dr. Sanjay Gupta',
        duration: '30 min',
        views: 28000,
        career: 'Medical',
        videoType: 'Expert Videos',
        locked: true,
        url: 'https://www.youtube.com/watch?v=3QfYx4kQXKM',
    },
    {
        title: 'Career in AI & Machine Learning',
        mentor: 'Prof. Sneha Patel',
        duration: '22 min',
        career: 'Technology',
        views: 18500,
        videoType: 'Career Videos',
        locked: true,
        url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    },
    {
        title: 'UX Design Career Path',
        mentor: 'Ms. Ria Kapoor',
        duration: '15 min',
        views: 7800,
        career: 'Design',
        videoType: 'Career Videos',
        locked: false,
        url: 'https://www.youtube.com/watch?v=Ovj4hFxko7c',
    },
    {
        title: 'MBA vs Direct Job After Graduation',
        mentor: 'Mr. Rohit Bansal',
        duration: '15 min',
        views: 9200,
        career: 'Business',
        videoType: 'Career Videos',
        locked: false,
        url: 'https://www.youtube.com/watch?v=9JrRQ1oQWQk',
    },
    {
        title: 'CAT Exam Strategy - Score 99+',
        mentor: 'Prof. Nitin Sharma',
        duration: '28 min',
        views: 32000,
        career: 'Business',
        videoType: 'Expert Videos',
        locked: true,
        url: 'https://www.youtube.com/watch?v=dwEKF6V36sU',
    },
    {
        title: 'Full Stack Development Roadmap',
        mentor: 'Mr. Harsh Agarwal',
        duration: '20 min',
        views: 15600,
        career: 'Technology',
        videoType: 'Expert Videos',
        locked: false,
        url: 'https://www.youtube.com/watch?v=zOjov-2OZ0E',
    },
    {
        title: 'Top Medical Specializations in India',
        mentor: 'Dr. Vivek Jain',
        duration: '20 min',
        views: 11000,
        career: 'Medical',
        videoType: 'Career Videos',
        locked: true,
        url: 'https://www.youtube.com/watch?v=3z4R2H4v1x8',
    },
];
export const mentors = [
    {
        name: 'Dr. Priya Sharma',
        specialty: 'Career Counselling',
        experience: '12 years',
        rating: '4.9',
        price: 'Rs 500 / session',
        tags: ['Counselling', 'Psychology'],
        bio: 'Expert career counsellor with 12 years of experience helping students find their ideal career paths.',
        accent: palette.primary,
        avatar: 'DP',
    },
    {
        name: 'Prof. Rahul Verma',
        specialty: 'Engineering Guidance',
        experience: '15 years',
        rating: '4.8',
        price: 'Rs 750 / session',
        tags: ['IIT', 'JEE', 'Engineering'],
        bio: 'Former professor with deep experience in engineering career guidance and competitive exam planning.',
        accent: palette.blue,
        avatar: 'RV',
    },
    {
        name: 'Ms. Anjali Singh',
        specialty: 'Design & Creative Arts',
        experience: '8 years',
        rating: '4.7',
        price: 'Rs 600 / session',
        tags: ['Design', 'UX', 'NID'],
        bio: 'A design mentor helping students explore creative career paths in product, UX, and media.',
        accent: palette.orange,
        avatar: 'AS',
    },
    {
        name: 'Mr. Vikram Patel',
        specialty: 'Business & MBA',
        experience: '10 years',
        rating: '4.9',
        price: 'Rs 800 / session',
        tags: ['MBA', 'CAT', 'Business'],
        bio: 'An MBA mentor guiding students toward business schools, management careers, and interview readiness.',
        accent: palette.secondary,
        avatar: 'VP',
    },
    {
        name: 'Dr. Meera Iyer',
        specialty: 'Medical Careers',
        experience: '18 years',
        rating: '4.8',
        price: 'Rs 700 / session',
        tags: ['NEET', 'Medical', 'AIIMS'],
        bio: 'A senior medical mentor helping students understand medical careers, NEET strategy, and college pathways.',
        accent: palette.green,
        avatar: 'MI',
    },
];
export const studyAbroadCountries = [
    {
        name: 'USA',
        flag: 'USA',
        description: 'Top universities, F-1 visa, strong STEM pathways.',
        detail: 'Home to top-ranked universities and known for MS, MBA, and PhD programs across technology, business, and research.',
        tuition: '$20,000 - $55,000 / year',
        living: '$10,000 - $18,000 / year',
        visa: 'F-1 Student Visa',
        intake: 'Fall, Spring, Summer',
        workRights: 'OPT up to 12 months, up to 36 months for STEM',
        topUniversities: ['MIT', 'Stanford University', 'Harvard University', 'Caltech'],
        popularCourses: ['MS Computer Science', 'MBA', 'MS Data Science', 'MS Electrical Engineering'],
        scholarships: ['Fulbright Scholarship', 'Hubert Humphrey Fellowship', 'Knight-Hennessy Scholars'],
        requirements: ['GRE or GMAT for select programs', 'TOEFL or IELTS', 'SOP and LORs', 'Financial proof'],
    },
    {
        name: 'United Kingdom',
        flag: 'UK',
        description: 'World-class education and one-year Masters programs.',
        detail: 'Known for globally recognised universities and faster postgraduate study timelines, especially for Masters courses.',
        tuition: 'GBP 10,000 - 38,000 / year',
        living: 'GBP 9,000 - 12,000 / year',
        visa: 'UK Student Visa',
        intake: 'September, January',
        workRights: '20 hrs per week during term and 2-year Graduate Route post-study',
        topUniversities: ['University of Oxford', 'University of Cambridge', 'Imperial College London', 'UCL'],
        popularCourses: ['MSc Finance', 'LLM', 'MBA', 'MSc Data Science'],
        scholarships: ['Chevening Scholarship', 'Commonwealth Scholarship', 'GREAT Scholarships'],
        requirements: ['IELTS or TOEFL', 'Academic transcripts', 'Personal statement', 'References'],
    },
    {
        name: 'Canada',
        flag: 'CAN',
        description: 'PR-friendly route with affordable postgraduate options.',
        detail: 'Popular for student-friendly immigration pathways, post-study work permits, and strong public university systems.',
        tuition: 'CAD 15,000 - 35,000 / year',
        living: 'CAD 10,000 - 15,000 / year',
        visa: 'Study Permit',
        intake: 'September, January, May',
        workRights: '20 hrs per week during study and PGWP up to 3 years',
        topUniversities: ['University of Toronto', 'UBC', 'McGill University', 'University of Waterloo'],
        popularCourses: ['MS Computer Science', 'MBA', 'MEng', 'MS Data Analytics'],
        scholarships: ['Vanier Canada Graduate Scholarship', 'Lester B. Pearson Scholarship', 'Ontario Graduate Scholarship'],
        requirements: ['IELTS or TOEFL', 'SOP', 'LORs', 'Financial proof'],
    },
    {
        name: 'Germany',
        flag: 'GER',
        description: 'Low-cost public education with strong engineering reputation.',
        detail: 'Known for public universities with minimal tuition fees and excellent opportunities in engineering and applied sciences.',
        tuition: 'EUR 250 - 500 / semester',
        living: 'EUR 10,000 - 12,000 / year',
        visa: 'German Student Visa',
        intake: 'Winter and Summer',
        workRights: '120 full days or 240 half days per year',
        topUniversities: ['TU Munich', 'RWTH Aachen', 'Heidelberg University', 'LMU Munich'],
        popularCourses: ['MS Mechanical Engineering', 'MS Computer Science', 'MS Automotive Engineering', 'MBA'],
        scholarships: ['DAAD Scholarship', 'Heinrich Boll Foundation', 'Deutschlandstipendium'],
        requirements: ['IELTS or TestDaF', 'APS Certificate for Indian students', 'Blocked account', 'Motivation letter'],
    },
    {
        name: 'Australia',
        flag: 'AUS',
        description: 'Research and innovation hub with strong post-study work options.',
        detail: 'A popular destination for IT, engineering, nursing, and business programs, with strong employability outcomes.',
        tuition: 'AUD 20,000 - 45,000 / year',
        living: 'AUD 21,000 / year',
        visa: 'Student Visa (subclass 500)',
        intake: 'February, July',
        workRights: '48 hrs per fortnight during study and post-study work options after graduation',
        topUniversities: ['University of Melbourne', 'University of Sydney', 'ANU', 'UNSW'],
        popularCourses: ['MS IT', 'MBA', 'MS Engineering', 'MS Nursing'],
        scholarships: ['Australia Awards', 'Destination Australia', 'Research Training Program'],
        requirements: ['IELTS or PTE', 'Academic transcripts', 'SOP', 'Health insurance', 'Financial proof'],
    },
    {
        name: 'New Zealand',
        flag: 'NZ',
        description: 'Great quality of life with globally respected universities.',
        detail: 'Known for safe student life, high quality education, and practical post-study work opportunities.',
        tuition: 'NZD 22,000 - 32,000 / year',
        living: 'NZD 15,000 - 20,000 / year',
        visa: 'New Zealand Student Visa',
        intake: 'February, July',
        workRights: '20 hrs per week during study and post-study work rights after graduation',
        topUniversities: ['University of Auckland', 'University of Otago', 'Victoria University of Wellington', 'Massey University'],
        popularCourses: ['MS Computer Science', 'MBA', 'MS Environmental Science', 'MS Engineering'],
        scholarships: ['New Zealand Excellence Awards', 'University-specific scholarships', 'SEG Scholarship'],
        requirements: ['IELTS or TOEFL', 'Academic transcripts', 'SOP', 'Financial proof', 'Health insurance'],
    },
];
export const notifications = [
    {
        id: '1',
        title: 'Mentor session confirmed',
        message: 'Your counselling slot is booked for Saturday at 4:00 PM.',
        time: '2h ago',
        unread: true,
    },
    {
        id: '2',
        title: 'Scholarship alert',
        message: 'The Aspire STEM scholarship applications close in 5 days.',
        time: 'Yesterday',
        unread: true,
    },
    {
        id: '3',
        title: 'New master class added',
        message: 'A fresh session on entrance exam planning is now available.',
        time: '2 days ago',
        unread: false,
    },
];
export const subscriptions = [
    {
        id: 'psychometric',
        name: 'Psychometric Test',
        price: 'Rs 1,500',
        description: 'One annual test, quick summary, and starter career suggestions.',
        features: ['1 Psychometric Test', 'Basic report', 'Career suggestions'],
    },
    {
        id: 'premium',
        name: 'Psychometric + Counselling',
        price: 'Rs 3,000',
        description: 'Unlock assessment, mentor booking, and master classes together.',
        features: ['Detailed report', '1-on-1 counselling', 'Mentor booking access', 'Master class access'],
        highestseller: true,
    },
    {
        id: 'infocentre',
        name: 'Infocentre Access',
        price: 'Rs 5,000',
        description: 'Unlock all core info modules except study abroad.',
        features: ['Psychometric test', 'Career library', 'Master class videos', 'Mentor booking', 'Scholarship info'],
        recommended: true,
    },
    {
        id: 'abroad',
        name: 'Study Abroad Access',
        price: 'Rs 2,500',
        description: 'Unlock only the Study Abroad module and counselling request flow.',
        features: ['Study Abroad module', 'Country details', 'Consultation request access'],
    },
];
export const settingsItems = [
    'Edit Profile',
    'Notification Preferences',
    'Dark Mode Preview',
    'Help Centre',
];
